# create ci / cd git hub

name: PR relese

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.7.7'
                channel: 'stable'
            - run: flutter --version
   