name: PR relese

on: pull_request

jobs:
  cancel:
    name: 'cancel information'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - run: flutter --version
  check:
    name: Check formatting
    runs-on: ubuntu-latest
    needs: cancel
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.7"
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Check lints
        run: flutter analyze
      - name: 🧪📊 Generate coverage report
        run: flutter test --coverage --coverage-path=coverage/lcov.info
      - name: Setup Bundle
        run: sudo gem install bundler
      - name: build android
        run: flutter build apk --debug && cd android && sudo fastlane add_plugin firebase_app_distribution && sudo fastlane android build
      - name: 🧪📊 Publish coverage report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: coverage/lcov.info
          title: 'Coverage Report'